name: CI

on:
  push:
    branches:
      - main
      - develop  # Add more branches as needed
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Qt dependencies
        run: sudo apt-get install -y qt5-default

      - name: Build
        run: qmake && make

      - name: Run Tests
        run: make test

